version: '3'

services:
  backend:
      build:
        dockerfile: Dockerfile
        context: .
      container_name: {{cookiecutter.project_slug}}
      depends_on:
        - db
      env_file: env/backend.env
      expose:
        - 8000
      volumes:
        - ./:/home/user/app
  db:
    container_name: postgres
    env_file: env/postgres.env
    image: postgres:12.2-alpine
    volumes:
      - .db:/var/lib/postgresql/data
  nginx:
    container_name: nginx
    depends_on:
      - backend
    image: nginx:1.17.10
    ports:
      - 8000:8000
    volumes:
      - ./:/home/user/app
      - ./nginx:/etc/nginx/conf.d
